# Generated by Django 5.0.6 on 2024-06-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('sub_loc', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WdpaOecm',
            fields=[
                ('wdpaid', models.IntegerField(primary_key=True, serialize=False)),
                ('wdpa_pid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('desig_eng', models.CharField(max_length=255)),
                ('desig_type', models.CharField(max_length=255)),
                ('marine', models.CharField(max_length=10)),
                ('rep_m_area', models.CharField(blank=True, max_length=255, null=True)),
                ('gis_m_area', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_area', models.CharField(blank=True, max_length=255, null=True)),
                ('gis_area', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('status_yr', models.IntegerField()),
                ('gov_type', models.CharField(max_length=255)),
                ('own_type', models.CharField(max_length=255)),
                ('mang_auth', models.CharField(max_length=255)),
                ('parent_iso3', models.CharField(max_length=3)),
            ],
        ),
    ]
