# Generated by Django 5.0.6 on 2024-06-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wdpaoecm',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wdpaoecm',
            name='wdpaid',
            field=models.IntegerField(),
        ),
    ]
