# Generated by Django 5.0.6 on 2024-07-01 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wdpaoecm_id_alter_wdpaoecm_wdpaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wdpaoecm',
            name='id',
        ),
        migrations.AddField(
            model_name='wdpaoecm',
            name='sub_loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AlterField(
            model_name='wdpaoecm',
            name='wdpaid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
