# Generated by Django 4.2.13 on 2024-07-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_wdpaoecm_id_wdpaoecm_sub_loc_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WdpaOecm",
            new_name="ProtectedArea",
        ),
    ]
