# Generated by Django 4.2.13 on 2024-07-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_wdpaoecm_protectedarea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectedarea",
            name="gis_area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="protectedarea",
            name="gis_m_area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="protectedarea",
            name="rep_area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="protectedarea",
            name="rep_m_area",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
